[versions]
kotlin = "2.2.21"
coroutines = "1.10.2"
compose = "1.9.3"
agp = "8.12.3"
android-minSdk = "26"
android-compileSdk = "36"
android-targetSdk = "36"
ios-deploymentTarget = "13.0"

[libraries]
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.7.1" }
jetbrains-androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version = "2.9.1" }
jetbrains-androidx-lyfecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version = "2.9.6" }
jetbrains-androidx-savedstate-compose = { module = "org.jetbrains.androidx.savedstate:savedstate-compose", version = "1.3.6" }
jetbrains-androidx-window-core = { module = "org.jetbrains.androidx.window:window-core", version = "1.5.0" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.17.0" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.12.0" }
androidx-window-window = { module = "androidx.window:window", version = "1.5.1" }
google-material-components = { module = "com.google.android.material:material", version = "1.13.0" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
androidApplication = { id = "com.android.application", version.ref = "agp" }